blank_issues_enabled: true
contact_links:
  - name: Beyond All Reason Official Discord
    url: https://discord.gg/beyond-all-reason
    about: You can raise more open suggestions on our Discord if you prefer that format of discussion
  - name: Engine Issues
    url: https://github.com/beyond-all-reason/spring/issues
    about: If you know your issue is specifically an engine problem, please report it here instead
  - name: Client Issues
    url: https://github.com/beyond-all-reason/BYAR-Chobby/issues
    about: If you have an issue specific to the lobby/client/menu, raise them here
  - name: Server Issues
    url: https://github.com/beyond-all-reason/teiserver/issues
    about: Issues specific to the master server