name: Feature Request
description: Use this template to submit an idea for an enhancement to the game
labels: ["Enhancement", "Awaiting Approval"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your suggestion
    validations:
      required: true

  - type: textarea
    id: problems
    attributes:
      label: Problems this will solve
      description: Explain the issues this feature would solve, or how it may impact the game
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other (optional)
      description: Optionally, you can provide implementation notes for developers, further ways this feature could be enhanced, potential issues this feature could introduce and how those problems could be mitigated, alternative solutions, or anything else you wish to add here